---
- name: Signature Management - Access Control
  hosts: localhost
  collections:
      - piolink.ansible_collection_webfrontk
  tasks:
      - name: Set Signature
        pio_sig_up:
            host: "{{ host }}"
            port: "{{ port }}"
            username: "{{ username }}"
            password: "{{ password }}"
            app_name: ALL
            sig_list:
                - sig_id: "110100001"
                  sig_status: "2"
                - sig_id: "110100002"
                  sig_status: "2"
...
